
import StudentPortalFooter from '@/src/components/Footer/StudentPortalFooter'
import StudentPortalNavbar from '@/src/components/Navbar/StudentPortalNavbar'
import type { Metadata } from 'next'



export const metadata: Metadata = {
        title: 'RCA | Student Portal',
        description: 'Generated by create next app',
}

export default function RootLayout({
        children,
}: {
        children: React.ReactNode
}) {
        return (
                <html lang="en">
                        <head>
                                <link rel='icon' href='/favicon.png' />
                        </head>
                        <body>
                                <StudentPortalNavbar />/
                                {children}
                             
                        </body>
                </html>
        )
}
